spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/insta_spring?useTimezone=true
      username: root
      password: root12345
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false